import type { Question } from '../../types'

/** Original practice questions for objective 8. */
export const hcpQuestions: Question[] = [
  {
    id: 'tfq-hcp-1',
    domainId: 'tf-hcp',
    topicId: 'tf-hcp-overview',
    kind: 'mcq',
    category: 'concept',
    difficulty: 'beginner',
    points: 1,
    prompt: 'Which block connects a configuration to HCP Terraform?',
    options: [
      { id: 'a', text: 'backend "remote"' },
      { id: 'b', text: 'cloud' },
      { id: 'c', text: 'hcp' },
      { id: 'd', text: 'organization' },
    ],
    correct: ['b'],
    explanation:
      'The `cloud` block sits inside the `terraform` block, requires an `organization`, and selects workspaces by `name` or `tags`. It replaces `backend` and the two are mutually exclusive - declaring both is an error.',
  },
  {
    id: 'tfq-hcp-2',
    domainId: 'tf-hcp',
    topicId: 'tf-hcp-overview',
    kind: 'multi',
    category: 'concept',
    difficulty: 'intermediate',
    points: 2,
    prompt:
      'Which of these does an HCP workspace have that a CLI workspace does not? (Select all that apply.)',
    options: [
      { id: 'a', text: 'Its own variables' },
      { id: 'b', text: 'Its own provider credentials' },
      { id: 'c', text: 'Its own state' },
      { id: 'd', text: 'Its own run history and permissions' },
      { id: 'e', text: 'Its own Terraform version setting' },
    ],
    correct: ['a', 'b', 'd', 'e'],
    explanation:
      'Both have their own state - that is what a CLI workspace is. Variables, credentials, run history, permissions and a pinned Terraform version are all specific to HCP workspaces, which is why they suit environment separation and CLI workspaces suit throwaway variants.',
  },
  {
    id: 'tfq-hcp-3',
    domainId: 'tf-hcp',
    topicId: 'tf-hcp-overview',
    kind: 'mcq',
    category: 'troubleshoot',
    difficulty: 'advanced',
    points: 3,
    prompt:
      'You export `AWS_ACCESS_KEY_ID` locally and run `terraform apply` against a remote-execution HCP workspace. Does it use your key?',
    options: [
      { id: 'a', text: 'Yes - the CLI forwards its environment to the run' },
      {
        id: 'b',
        text: 'No - the run reads the workspace’s environment variables; your shell is not uploaded',
      },
      { id: 'c', text: 'Yes, but only if the workspace has no credentials of its own' },
      { id: 'd', text: 'It fails, because two credential sources conflict' },
    ],
    correct: ['b'],
    explanation:
      'Only the configuration directory is uploaded. The run executes in HCP using the workspace’s own variables, which is precisely the security benefit: credentials live in one audited place rather than on every machine. In *local* execution mode the opposite is true - your environment is exactly what is used.',
  },
  {
    id: 'tfq-hcp-4',
    domainId: 'tf-hcp',
    topicId: 'tf-hcp-workspaces-and-projects',
    kind: 'mcq',
    category: 'concept',
    difficulty: 'intermediate',
    points: 2,
    prompt: 'How does one configuration serve several HCP workspaces?',
    options: [
      { id: 'a', text: 'By listing several names in workspaces { name = [...] }' },
      { id: 'b', text: 'By binding with tags, then using terraform workspace select' },
      { id: 'c', text: 'By declaring several cloud blocks' },
      { id: 'd', text: 'It cannot - one configuration binds to one workspace' },
    ],
    correct: ['b'],
    explanation:
      '`workspaces { tags = ["network"], project = "Platform" }` binds to every matching workspace, and `terraform workspace select` chooses one. Binding by `name` locks the configuration to a single workspace.',
  },
  {
    id: 'tfq-hcp-5',
    domainId: 'tf-hcp',
    topicId: 'tf-hcp-workspaces-and-projects',
    kind: 'mcq',
    category: 'concept',
    difficulty: 'intermediate',
    points: 2,
    prompt: 'Twenty workspaces need the same provider credentials. What is the right mechanism?',
    options: [
      { id: 'a', text: 'Set the variables individually on each workspace' },
      { id: 'b', text: 'A variable set applied to the relevant project or workspaces' },
      { id: 'c', text: 'A shared terraform.tfvars committed to the repository' },
      { id: 'd', text: 'A run trigger from a credentials workspace' },
    ],
    correct: ['b'],
    explanation:
      'Variable sets apply variables to a project, to listed workspaces, or globally, and workspace-level variables override them where one genuinely needs something different. Better still, put dynamic credentials in the set so there is no stored secret to rotate across twenty workspaces.',
  },
  {
    id: 'tfq-hcp-6',
    domainId: 'tf-hcp',
    topicId: 'tf-hcp-collaboration-governance',
    kind: 'mcq',
    category: 'concept',
    difficulty: 'intermediate',
    points: 2,
    prompt: 'What are the three Sentinel enforcement levels?',
    options: [
      { id: 'a', text: 'warn, block, audit' },
      { id: 'b', text: 'advisory, soft-mandatory, hard-mandatory' },
      { id: 'c', text: 'advisory, mandatory' },
      { id: 'd', text: 'low, medium, high' },
    ],
    correct: ['b'],
    explanation:
      '`advisory` warns only, `soft-mandatory` blocks but an authorised user may override (and it is recorded), `hard-mandatory` blocks with no override. OPA has two levels: advisory and mandatory.',
  },
  {
    id: 'tfq-hcp-7',
    domainId: 'tf-hcp',
    topicId: 'tf-hcp-collaboration-governance',
    kind: 'mcq',
    category: 'concept',
    difficulty: 'advanced',
    points: 2,
    prompt: 'What do Sentinel and OPA policies evaluate?',
    options: [
      { id: 'a', text: 'The HCL source text of the configuration' },
      { id: 'b', text: 'The plan JSON - the same structure terraform show -json produces' },
      { id: 'c', text: 'The state file after the apply' },
      { id: 'd', text: 'The provider schema' },
    ],
    correct: ['b'],
    explanation:
      'Because they see the plan rather than the source, a policy checks what would actually happen - including provider defaults the author never wrote. It also means you can develop and test a policy entirely offline against a captured `plan.json`.',
  },
  {
    id: 'tfq-hcp-8',
    domainId: 'tf-hcp',
    topicId: 'tf-hcp-collaboration-governance',
    kind: 'mcq',
    category: 'concept',
    difficulty: 'advanced',
    points: 2,
    prompt: 'Why introduce a new policy as `advisory` rather than `hard-mandatory`?',
    options: [
      { id: 'a', text: 'Because hard-mandatory requires a higher plan tier' },
      {
        id: 'b',
        text: 'Because a new policy almost always has false positives, and blocking legitimate work while you find them is expensive',
      },
      { id: 'c', text: 'Because advisory policies run faster' },
      { id: 'd', text: 'Because Sentinel requires it for the first fourteen days' },
    ],
    correct: ['b'],
    explanation:
      'Run it advisory, review every warning, fix real violations and correct the policy where it was wrong, then promote it once warnings are consistently zero. Measure before you enforce, or the control gets disabled the first time it blocks something urgent.',
  },
  {
    id: 'tfq-hcp-9',
    domainId: 'tf-hcp',
    topicId: 'tf-hcp-integrations',
    kind: 'mcq',
    category: 'concept',
    difficulty: 'intermediate',
    points: 2,
    prompt: 'What is a speculative plan?',
    options: [
      { id: 'a', text: 'A plan run with -refresh=false, so it may be inaccurate' },
      { id: 'b', text: 'A plan-only run that can never be applied' },
      { id: 'c', text: 'A plan queued automatically every hour to detect drift' },
      { id: 'd', text: 'A plan that estimates cost rather than changes' },
    ],
    correct: ['b'],
    explanation:
      'Speculative plans are what make pull-request plans safe: a contribution from an untrusted branch or a fork can be planned and reviewed with no possibility of it changing anything.',
  },
  {
    id: 'tfq-hcp-10',
    domainId: 'tf-hcp',
    topicId: 'tf-hcp-integrations',
    kind: 'mcq',
    category: 'troubleshoot',
    difficulty: 'advanced',
    points: 3,
    prompt:
      'A remote run cannot reach a database with no public endpoint. What is the correct solution?',
    options: [
      { id: 'a', text: 'Switch the workspace to local execution' },
      {
        id: 'b',
        text: 'Run an HCP Terraform agent inside the network and set execution mode to agent',
      },
      { id: 'c', text: 'Expose the database publicly and restrict it by IP' },
      { id: 'd', text: 'Use a run task to proxy the connection' },
    ],
    correct: ['b'],
    explanation:
      'An agent polls HCP outbound, so the run executes inside your network with no inbound firewall rule, and every other feature - policy, history, RBAC, dynamic credentials - keeps working. Local execution would put cloud credentials back on laptops and lose the audit trail for your most sensitive workspace.',
  },
  {
    id: 'tfq-hcp-11',
    domainId: 'tf-hcp',
    topicId: 'tf-hcp-integrations',
    kind: 'mcq',
    category: 'concept',
    difficulty: 'advanced',
    points: 3,
    prompt: 'How do dynamic provider credentials remove the need for a stored cloud secret?',
    options: [
      { id: 'a', text: 'HCP encrypts the stored key with a customer-managed key' },
      {
        id: 'b',
        text: 'HCP presents a signed workload identity token, which the cloud exchanges for short-lived credentials',
      },
      { id: 'c', text: 'The agent holds the credentials instead of the workspace' },
      { id: 'd', text: 'Terraform generates a key pair per run and registers it automatically' },
    ],
    correct: ['b'],
    explanation:
      'You configure HCP’s OIDC issuer as an identity provider in the cloud, and a role whose trust policy accepts it - scoped by subject to a specific organisation, project and workspace. The subject scoping is essential: without it any workspace could assume the role, defeating workspace isolation.',
  },
  {
    id: 'tfq-hcp-12',
    domainId: 'tf-hcp',
    topicId: 'tf-hcp-integrations',
    kind: 'mcq',
    category: 'troubleshoot',
    difficulty: 'intermediate',
    points: 2,
    prompt: 'In a monorepo, every commit queues a run in every HCP workspace. What is missing?',
    options: [
      { id: 'a', text: 'A working directory setting' },
      { id: 'b', text: 'Trigger patterns on each workspace' },
      { id: 'c', text: 'A run trigger between the workspaces' },
      { id: 'd', text: 'Separate VCS connections per workspace' },
    ],
    correct: ['b'],
    explanation:
      'Trigger patterns such as `applications/api/**` and `modules/shared/**` restrict which paths queue a run. Without them the noise trains people to ignore run notifications, which is worse than the wasted compute.',
  },
]
